Neos:
  Neos:
    fusion:
      autoInclude:
        KaufmannDigital.CookieConsent: true
  Fusion:
    defaultContext:
      'LinkBuilder': 'KaufmannDigital\CookieConsent\Eel\Helper\LinkBuildingHelper'

KaufmannDigital:
  CookieConsent:
    enable: true
    includeJavaScript: true
    includeCss: true
    type: ''
    policyPageNode: ''
    translations:
      package: 'KaufmannDigital.CookieConsent'
      source: 'Main'
    position: 'bottom'
    theme: 'block'
    palette:
      popup:
        background: '#000'
        text: '#fff'
      button:
        background: '#f1d600'
        text: '#000'
